name: lookwise_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Or whatever version you have
  intl: ^0.18.1 # Assuming you've already added this for the previous error
  http: ^1.2.1 # Use the latest stable version of http
  geolocator: ^10.1.0 # ✏️ Replace with lower version
  geocoding: ^2.0.5

  permission_handler: ^11.0.1 # ✏️ Replace with lower version




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cool_veins.png
    - assets/images/warm_veins.png
    - assets/images/neutral_veins.png
    - assets/images/body_measurements_diagram.png
    - assets/images/face_oval.png      # <--- ADD THESE LINES
    - assets/images/face_square.png
    - assets/images/face_heart.png
    - assets/images/face_round.png
    - assets/images/face_diamond.png
    - assets/images/features_background_image.png
    - assets/images/girls_cutout.png
    - assets/images/profile_icon_design.png
    - assets/images/hot_weather.jpg
    - assets/images/normal_weather.jpg
    - assets/images/rainy_weather.jpg
    - assets/images/cold_weather.jpg
    - assets/images/fog_weather.jpg
  # Ensure you include all individual image paths here